version: '2'
services:
    gardle-app:
        image: gardle/gardle:0.4.4
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=dev,swagger,generateQuickData
            - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
            - SPRING_DATASOURCE_URL=jdbc:postgresql://airgnb-postgresql:5432/airgnb
            - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
            - SPRING_DATA_JEST_URI=http://airgnb-elasticsearch:9200
            - JASYPT_ENCRYPTOR_PASSWORD=vyzT9EttTsGHSr5n54e7
        ports:
            - 8080:8080
    airgnb-postgresql:
        image: postgres:11.5
        # volumes:
        #     - ~/volumes/jhipster/airgnb/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=airgnb
            - POSTGRES_PASSWORD=password
        #        - POSTGRES_PASSWORD=password
        ports:
            - 5432:5432
