version: '2'
services:
    airgnb-postgresql:
        image: postgres:11.5
        # volumes:
        #     - ~/volumes/jhipster/airgnb/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=airgnb
            - POSTGRES_PASSWORD=password
        ports:
            - 5432:5432
